# Generated by Django 5.2 on 2026-01-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item del carrito', 'verbose_name_plural': 'Items del carrito'},
        ),
    ]
