# Generated by Django 5.2 on 2026-01-07 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_direccionenvio_favorito_resenaproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('DINERS', 'Diners Club'), ('AMEX', 'American Express')], max_length=20)),
                ('ultimos_digitos', models.CharField(help_text='Solo los últimos 4 números', max_length=4)),
                ('fecha_vencimiento', models.CharField(help_text='Formato MM/YY', max_length=5)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
