# Generated by Django 5.2 on 2026-01-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_metodopago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResenaProducto',
        ),
    ]
