# Generated by Django 5.2 on 2026-01-03 08:48

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=90)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_bodeg_es_acti_97995a_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_bodega_nombre_ci')],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('prefijo_sku', models.CharField(max_length=10, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_categ_es_acti_2c36b8_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_categoria_nombre_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('prefijo_sku'), name='unique_categoria_prefijo_ci')],
            },
        ),
        migrations.CreateModel(
            name='ClaseProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clase de producto',
                'verbose_name_plural': 'Clases de producto',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_clase_es_acti_66ca0a_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_claseprod_codigo_ci')],
            },
        ),
        migrations.CreateModel(
            name='EstadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('es_vendible', models.BooleanField(default=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('marca_disponible', models.BooleanField(default=False)),
                ('marca_agotado', models.BooleanField(default=False)),
                ('marca_bloqueado', models.BooleanField(default=False)),
                ('marca_vencido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado de lote',
                'verbose_name_plural': 'Estados de lote',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_estad_es_acti_579eb1_idx'), models.Index(fields=['es_vendible'], name='miapp_estad_es_vend_18192f_idx'), models.Index(fields=['marca_disponible'], name='miapp_estad_marca_d_422c05_idx'), models.Index(fields=['marca_agotado'], name='miapp_estad_marca_a_068edd_idx'), models.Index(fields=['marca_vencido'], name='miapp_estad_marca_v_0da4ab_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_estadolote_codigo_ci')],
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=90, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de pedido',
                'verbose_name_plural': 'Estados de pedido',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_estad_es_acti_a36a50_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_estadopedido_codigo_ci')],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_marca_es_acti_c721be_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_marca_nombre_ci')],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_pais_es_acti_f94bc3_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo_iso'), name='unique_pais_codigo_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_pais_nombre_ci')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('numero_identificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(blank=True, max_length=150, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='miapp.pais')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_origen', to='miapp.bodega', verbose_name='Bodega de Salida Predefinida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='miapp.cliente')),
                ('estado_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='miapp.estadopedido')),
                ('pedido_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_derivados', to='miapp.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PerfilCaducidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('requiere_caducidad', models.BooleanField(default=True)),
                ('dias_bloqueo_previo', models.PositiveIntegerField(default=0)),
                ('estrategia_requerida', models.CharField(blank=True, choices=[('FIFO', 'FIFO'), ('FEFO', 'FEFO')], max_length=10, null=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de caducidad',
                'verbose_name_plural': 'Perfiles de caducidad',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_perfi_es_acti_0d3ab7_idx'), models.Index(fields=['requiere_caducidad'], name='miapp_perfi_requier_609290_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_perfilcaducidad_codigo_ci')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_negocio', models.CharField(choices=[('ADMIN_SISTEMA', 'ADMIN_SISTEMA'), ('OPERADOR_OPERACIONES', 'OPERADOR_OPERACIONES'), ('VENDEDOR', 'VENDEDOR')], max_length=30)),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='miapp.bodega')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estrategia_salida', models.CharField(choices=[('FIFO', 'First In, First Out (Primero en Entrar)'), ('FEFO', 'First Expired, First Out (Primero en Vencer)')], default='FIFO', max_length=10)),
                ('notas_manejo', models.CharField(blank=True, max_length=300, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.categoria')),
                ('clase_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.claseproducto')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.impuesto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.marca')),
                ('perfil_caducidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.perfilcaducidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_seguridad', models.IntegerField(default=0)),
                ('fecha_ultimo_movimiento', models.DateTimeField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='miapp.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='miapp.producto')),
            ],
            options={
                'verbose_name': 'Inventario de producto',
                'verbose_name_plural': 'Inventarios de producto',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('orden', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='miapp.producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_atendida', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_transferencia', to='miapp.producto')),
            ],
            options={
                'verbose_name': 'Detalle de transferencia',
                'verbose_name_plural': 'Detalles de transferencia',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_atendida', models.IntegerField(default=0)),
                ('estado_logistico', models.CharField(choices=[('DISPONIBLE', 'Listo para despacho'), ('ESPERANDO_TRASPASO', 'Stock faltante (Requiere Traspaso)'), ('EN_TRANSITO', 'En camino desde otra bodega'), ('ATENDIDO', 'Entregado totalmente')], default='DISPONIBLE', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('subtotal_costo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='miapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('numero_identificacion', models.CharField(max_length=30, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='miapp.pais')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.bodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='StockLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=120, null=True)),
                ('lote_proveedor', models.CharField(blank=True, max_length=120, null=True)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('costo_compra_lote', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('archivado', models.BooleanField(default=False)),
                ('estado_lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='miapp.estadolote')),
                ('lote_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_derivados', to='miapp.stocklote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='miapp.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='miapp.proveedor')),
            ],
            options={
                'verbose_name': 'Stock por lote',
                'verbose_name_plural': 'Stock por lote',
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='miapp.detalletransferenciainterna')),
                ('stock_lote_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_lote_recibidas', to='miapp.stocklote')),
                ('stock_lote_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_lote_salida', to='miapp.stocklote')),
            ],
            options={
                'verbose_name': 'Detalle transferencia por lote',
                'verbose_name_plural': 'Detalles transferencia por lote',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miapp.producto')),
                ('lote_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.stocklote')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=90, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de almacenamiento',
                'verbose_name_plural': 'Tipos de almacenamiento',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_tipoa_es_acti_011218_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_tipoalm_codigo_ci')],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_almacenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.tipoalmacenamiento'),
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de cliente',
                'verbose_name_plural': 'Tipos de cliente',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_tipoc_es_acti_aff6da_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_tipocliente_codigo_ci')],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='miapp.tipocliente'),
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=90, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('es_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de identificación',
                'verbose_name_plural': 'Tipos de identificación',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_tipoi_es_acti_9d29b5_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_tipoident_codigo_ci')],
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='miapp.tipoidentificacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='miapp.tipoidentificacion'),
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('afecta_stock', models.BooleanField(default=True)),
                ('es_entrada', models.BooleanField(default=False)),
                ('es_salida', models.BooleanField(default=False)),
                ('es_sistema', models.BooleanField(default=False, editable=False)),
                ('requiere_pedido', models.BooleanField(default=False)),
                ('requiere_motivo_detallado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de movimiento',
                'verbose_name_plural': 'Tipos de movimiento',
                'indexes': [models.Index(fields=['es_activo'], name='miapp_tipom_es_acti_582e09_idx'), models.Index(fields=['es_entrada'], name='miapp_tipom_es_entr_215273_idx'), models.Index(fields=['es_salida'], name='miapp_tipom_es_sali_7db2f8_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_tipomov_codigo_ci')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('stock_antes', models.IntegerField(blank=True, null=True)),
                ('stock_despues', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('motivo', models.CharField(blank=True, max_length=300, null=True)),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='miapp.bodega')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='miapp.bodega')),
                ('detalle_transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='miapp.detalletransferencialote')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='miapp.inventarioproducto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='miapp.pedido')),
                ('stock_lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='miapp.stocklote')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='miapp.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POR_PEDIDO', 'Por pedido'), ('CONTINGENCIA', 'Contingencia'), ('REABASTECIMIENTO', 'Reabastecimiento')], db_index=True, default='POR_PEDIDO', max_length=20)),
                ('codigo', models.CharField(editable=False, max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('SOLICITADA', 'Solicitada'), ('EN_PREPARACION', 'En preparación'), ('DESPACHADA', 'Despachada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='miapp.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='miapp.bodega')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_internas', to='miapp.pedido')),
                ('usuario_ejecuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones_transferencia', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_transferencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detalletransferenciainterna',
            name='transferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp.transferenciainterna'),
        ),
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_fila', models.PositiveIntegerField()),
                ('codigo_celda', models.CharField(editable=False, max_length=30, unique=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='miapp.rack')),
            ],
            options={
                'verbose_name': 'Ubicación física',
                'verbose_name_plural': 'Ubicaciones físicas',
            },
        ),
        migrations.AddField(
            model_name='stocklote',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='miapp.ubicacionfisica'),
        ),
        migrations.AddField(
            model_name='detalletransferencialote',
            name='ubicacion_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_lote_entrada', to='miapp.ubicacionfisica'),
        ),
        migrations.CreateModel(
            name='ZonaAlmacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('es_activo', models.BooleanField(default=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='miapp.bodega')),
                ('tipo_almacenamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='miapp.tipoalmacenamiento')),
            ],
            options={
                'verbose_name': 'Zona de almacenamiento',
                'verbose_name_plural': 'Zonas de almacenamiento',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='miapp.zonaalmacenamiento'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['codigo'], name='miapp_pedid_codigo_4c41e9_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido', 'fecha_creacion'], name='miapp_pedid_estado__5c1931_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='miapp_pedid_usuario_f650c4_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_pedido_codigo_ci'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_pedido_total_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('total_costo__gte', 0)), name='ck_pedido_costo_no_neg'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['rol_negocio'], name='miapp_perfi_rol_neg_da4af3_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['bodega'], name='miapp_perfi_bodega__677bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioproducto',
            index=models.Index(fields=['bodega', 'producto'], name='miapp_inven_bodega__d29807_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'bodega'), name='unique_inventario_producto_bodega'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='ck_inventario_stock_actual_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='ck_inventario_stock_minimo_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='inventarioproducto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_seguridad__gte', 0)), name='ck_inventario_stock_seguridad_no_neg'),
        ),
        migrations.AddIndex(
            model_name='imagenproducto',
            index=models.Index(fields=['producto', 'orden'], name='miapp_image_product_3f46f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagenproducto',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('producto',), name='unique_imagen_principal_por_producto'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['es_activo'], name='miapp_produ_es_acti_147082_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'marca'], name='miapp_produ_categor_cd94fd_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['perfil_caducidad'], name='miapp_produ_perfil__60fa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estrategia_salida'], name='miapp_produ_estrate_d6b9f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo_sku'), name='unique_producto_sku_ci'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', 0)), name='ck_producto_precio_venta_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('costo_compra__gte', 0)), name='ck_producto_costo_compra_no_neg'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['es_activo'], name='miapp_prove_es_acti_e547cc_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['pais'], name='miapp_prove_pais_id_42e605_idx'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_proveedor_nombre_ci'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('numero_identificacion'), name='unique_proveedor_ident_ci'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo'], name='miapp_clien_codigo_1ec0ce_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['es_activo'], name='miapp_clien_es_acti_407a7c_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['numero_identificacion'], name='miapp_clien_numero__8974b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('numero_identificacion'), condition=models.Q(('numero_identificacion__isnull', False), models.Q(('numero_identificacion', ''), _negated=True)), name='unique_cliente_ident_ci'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['codigo'], name='miapp_movim_codigo_d1f019_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='miapp_movim_fecha_993e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento', 'fecha'], name='miapp_movim_tipo_mo_2f86d5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['inventario', 'fecha'], name='miapp_movim_inventa_d538bd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['pedido'], name='miapp_movim_pedido__4bf0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['detalle_transferencia'], name='miapp_movim_detalle_72f66e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['usuario', 'fecha'], name='miapp_movim_usuario_0d5280_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_origen', 'fecha'], name='miapp_movim_bodega__892d70_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['bodega_destino', 'fecha'], name='miapp_movim_bodega__27a7ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_movimiento_codigo_ci'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_mov_cantidad_gt0'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('pedido__isnull', False), ('detalle_transferencia__isnull', False), _negated=True), name='ck_mov_no_pedido_y_transferencia_a_la_vez'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('detalle_transferencia__isnull', True), models.Q(('bodega_origen__isnull', False), ('bodega_destino__isnull', False)), _connector='OR'), name='ck_mov_transferencia_requiere_bodegas'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('detalle_transferencia__isnull', True), models.Q(('bodega_origen', models.F('bodega_destino')), _negated=True), _connector='OR'), name='ck_mov_transferencia_origen_destino_distintos'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_antes__isnull', True), ('stock_antes__gte', 0), _connector='OR'), name='ck_mov_stock_antes_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_despues__isnull', True), ('stock_despues__gte', 0), _connector='OR'), name='ck_mov_stock_despues_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='transferenciainterna',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='unique_transferencia_codigo_ci'),
        ),
        migrations.AddConstraint(
            model_name='transferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('bodega_origen', models.F('bodega_destino')), _negated=True), name='ck_transferencia_bodegas_distintas'),
        ),
        migrations.AddConstraint(
            model_name='transferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('tipo', 'POR_PEDIDO'), ('pedido__isnull', True), _negated=True), name='ck_transferencia_por_pedido_requiere_pedido'),
        ),
        migrations.AddConstraint(
            model_name='transferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('pedido__isnull', False), models.Q(('tipo', 'POR_PEDIDO'), _negated=True), _negated=True), name='ck_transferencia_si_hay_pedido_tipo_por_pedido'),
        ),
        migrations.AddIndex(
            model_name='detalletransferenciainterna',
            index=models.Index(fields=['transferencia'], name='miapp_detal_transfe_ea3d47_idx'),
        ),
        migrations.AddIndex(
            model_name='detalletransferenciainterna',
            index=models.Index(fields=['producto'], name='miapp_detal_product_20b68b_idx'),
        ),
        migrations.AddConstraint(
            model_name='detalletransferenciainterna',
            constraint=models.UniqueConstraint(fields=('transferencia', 'producto'), name='unique_detalle_transferencia_producto'),
        ),
        migrations.AddConstraint(
            model_name='detalletransferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_solicitada__gt', 0)), name='ck_transferencia_cant_solicitada_gt0'),
        ),
        migrations.AddConstraint(
            model_name='detalletransferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_atendida__gte', 0)), name='ck_transferencia_cant_atendida_gte0'),
        ),
        migrations.AddConstraint(
            model_name='detalletransferenciainterna',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_atendida__lte', models.F('cantidad_solicitada'))), name='ck_transferencia_atendida_lte_solicitada'),
        ),
        migrations.AddIndex(
            model_name='ubicacionfisica',
            index=models.Index(fields=['codigo_celda'], name='miapp_ubica_codigo__ec7d15_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionfisica',
            index=models.Index(fields=['es_activo'], name='miapp_ubica_es_acti_4ebc27_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacionfisica',
            index=models.Index(fields=['rack', 'nivel_fila'], name='miapp_ubica_rack_id_8a33d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionfisica',
            constraint=models.UniqueConstraint(fields=('rack', 'nivel_fila'), name='unique_ubicacion_rack_nivel'),
        ),
        migrations.AddConstraint(
            model_name='ubicacionfisica',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_fila__gte', 1)), name='ck_ubicacion_nivel_fila_gte_1'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['producto', 'estado_lote'], name='miapp_stock_product_9da98c_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['producto', 'fecha_caducidad'], name='miapp_stock_product_a363be_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['ubicacion'], name='miapp_stock_ubicaci_130882_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['lote'], name='miapp_stock_lote_9cfb02_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['archivado'], name='miapp_stock_archiva_20e775_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['proveedor'], name='miapp_stock_proveed_738a84_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklote',
            index=models.Index(fields=['lote_origen'], name='miapp_stock_lote_or_9f71d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.UniqueConstraint(fields=('producto', 'lote', 'ubicacion'), name='uq_lote_producto_ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='ck_lote_cantidad_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='stocklote',
            constraint=models.CheckConstraint(condition=models.Q(('costo_compra_lote__gte', 0)), name='ck_lote_costo_no_neg'),
        ),
        migrations.AddIndex(
            model_name='detalletransferencialote',
            index=models.Index(fields=['detalle'], name='miapp_detal_detalle_94b010_idx'),
        ),
        migrations.AddIndex(
            model_name='detalletransferencialote',
            index=models.Index(fields=['stock_lote_origen'], name='miapp_detal_stock_l_462e67_idx'),
        ),
        migrations.AddIndex(
            model_name='detalletransferencialote',
            index=models.Index(fields=['ubicacion_destino'], name='miapp_detal_ubicaci_1b9b0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='detalletransferencialote',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_trf_lote_cantidad_gt0'),
        ),
        migrations.AddIndex(
            model_name='zonaalmacenamiento',
            index=models.Index(fields=['es_activo'], name='miapp_zonaa_es_acti_ccebec_idx'),
        ),
        migrations.AddIndex(
            model_name='zonaalmacenamiento',
            index=models.Index(fields=['bodega', 'nombre'], name='miapp_zonaa_bodega__710392_idx'),
        ),
        migrations.AddConstraint(
            model_name='zonaalmacenamiento',
            constraint=models.UniqueConstraint(fields=('bodega', 'codigo'), name='unique_zona_bodega_codigo'),
        ),
        migrations.AddConstraint(
            model_name='zonaalmacenamiento',
            constraint=models.UniqueConstraint(fields=('bodega', 'nombre'), name='unique_zona_bodega_nombre_ci'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['es_activo'], name='miapp_rack_es_acti_96b695_idx'),
        ),
        migrations.AddIndex(
            model_name='rack',
            index=models.Index(fields=['zona', 'codigo'], name='miapp_rack_zona_id_f9bab7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('zona', 'codigo'), name='unique_rack_zona_codigo'),
        ),
    ]
