# Generated by Django 5.2 on 2026-01-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciainterna',
            name='tipo',
            field=models.CharField(choices=[('POR_PEDIDO', 'Por pedido'), ('CONTINGENCIA', 'Contingencia'), ('REABASTECIMIENTO', 'Reabastecimiento'), ('MANUAL', 'Reabastecimiento Manual (Push)')], db_index=True, default='POR_PEDIDO', max_length=20),
        ),
    ]
