# Generated by Django 5.2 on 2026-01-04 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_transferenciainterna_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('ERP', 'Venta Interna / Mostrador'), ('WEB', 'E-commerce Online')], default='ERP', max_length=10, verbose_name='Canal de Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_publico',
            field=models.BooleanField(default=True, verbose_name='Vender en la web'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol_negocio',
            field=models.CharField(choices=[('ADMIN_SISTEMA', 'ADMIN_SISTEMA'), ('OPERADOR_OPERACIONES', 'OPERADOR_OPERACIONES'), ('VENDEDOR', 'VENDEDOR'), ('CLIENTE', 'CLIENTE WEB')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
