# Generated by Django 5.2 on 2026-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_pedido_origen_producto_es_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real'),
        ),
    ]
