# Generated by Django 5.2 on 2026-01-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_pedido_fecha_entrega'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
        migrations.RemoveConstraint(
            model_name='imagenproducto',
            name='unique_imagen_principal_por_producto',
        ),
    ]
